# Generated by Django 6.1 on 2026-08-25 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='Employees',
        ),
    ]
