# Generated by Django 6.1 on 2026-08-26 00:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employees', '0002_alter_employee_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.DateField()),
                ('fecha_liquidacion', models.DateField(auto_now_add=True)),
                ('fecha_pago_prevista', models.DateField(blank=True, null=True)),
                ('importe_recibo', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('sueldo_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('moneda', models.CharField(default='ARS', max_length=3)),
                ('recibo_entregado', models.BooleanField(default=False)),
                ('fecha_entrega_recibo', models.DateField(blank=True, null=True)),
                ('recibo_firmado', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('anulado', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salaries', to='Employees.employee')),
            ],
            options={
                'db_table': 'Salaries',
                'ordering': ['-periodo', 'employee__apellido', 'employee__nombre'],
            },
        ),
        migrations.CreateModel(
            name='SalaryConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('HABER', 'Haber'), ('DESCUENTO', 'Descuento')], max_length=20)),
                ('categoria', models.CharField(choices=[('SUELDO_BASE', 'Sueldo base'), ('HORAS_EXTRA', 'Horas extra'), ('BONIFICACION', 'Bonificación'), ('PREMIO', 'Premio'), ('COMISION', 'Comisión'), ('VIATICOS', 'Viáticos'), ('ANTICIPO', 'Anticipo'), ('EMBARGO', 'Embargo'), ('DESCUENTO', 'Descuento'), ('AJUSTE', 'Ajuste'), ('OTRO', 'Otro')], max_length=30)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='Salaries.salary')),
            ],
            options={
                'db_table': 'SalaryConcepts',
                'ordering': ['tipo', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TRANSFERENCIA', 'Transferencia'), ('EFECTIVO', 'Efectivo'), ('AJUSTE_EFECTIVO', 'Ajuste en efectivo'), ('OTRO', 'Otro')], max_length=30)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fecha', models.DateField()),
                ('banco', models.CharField(blank=True, max_length=150, null=True)),
                ('referencia', models.CharField(blank=True, max_length=255, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Salaries.salary')),
            ],
            options={
                'db_table': 'SalaryPayments',
                'ordering': ['fecha', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='salary',
            constraint=models.UniqueConstraint(fields=('employee', 'periodo'), name='unique_employee_salary_period'),
        ),
    ]
