# Generated by Django 6.1 on 2026-08-27 18:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salaries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarypayment',
            name='salary',
        ),
        migrations.RenameField(
            model_name='salary',
            old_name='sueldo_total',
            new_name='ajuste_efectivo',
        ),
        migrations.CreateModel(
            name='SalaryDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='Salaries.salary')),
            ],
            options={
                'db_table': 'SalaryDiscounts',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='SalaryConcept',
        ),
        migrations.DeleteModel(
            name='SalaryPayment',
        ),
    ]
